version: "3"

services:
  bot_service:
    image: forevka/recaptcha-bot:dev
    profiles:
      - production
    depends_on: 
      - redis
    build:
      context: .
    env_file:
      - ./.env
    command: ["python3", "bot.py"]
    
  web_service:
    image: forevka/recaptcha-bot:dev
    profiles:
      - production
    depends_on: 
      - redis
    build:
      context: .
    env_file:
      - ./.env
    command: ["uvicorn", "web:app", "--host", "0.0.0.0", "--port", "${INTERNAL_WEB_PORT}"]
    ports:
      - "80:${INTERNAL_WEB_PORT}"

  redis:
    image: bitnami/redis:latest
    profiles:
      - production
      - development
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data

  redis-browser:
    profiles:
      - development
    depends_on: 
      - redis
    image: marian/rebrow
    ports: 
      - "5001:5001"


volumes:
  redis-data: