version: "3"

services:
  bot_service:
    image: forevka/recaptcha-bot:dev
    profiles:
      - production
    depends_on: 
      - redis
      - postgresql
    build:
      context: .
    env_file:
      - ./.env
    command: ["python3", "bot_service.py"]
    
  web_service:
    image: forevka/recaptcha-bot:dev
    profiles:
      - production
    depends_on: 
      - redis
      - postgresql
    build:
      context: .
    env_file:
      - ./.env
    command: ["uvicorn", "web_service:app", "--host", "0.0.0.0", "--port", "${INTERNAL_WEB_PORT}"]
    ports:
      - "80:${INTERNAL_WEB_PORT}"

  redis:
    image: bitnami/redis:latest
    profiles:
      - production
      - development
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data

  redis-browser:
    profiles:
      - development
    depends_on: 
      - redis
    image: marian/rebrow
    ports: 
      - "5001:5001"

  postgresql:
    image: "postgres:12"
    profiles:
      - production
    env_file:
      - ./.env
    ports:
      - "5437:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/


volumes:
  redis-data:
  database-data: